# rmdpt_collector/search_terms.py
from itertools import chain

# === Rare Mental Diseases (corrected capitalization, obvious variants) ===
DISEASE_SYNONYMS = {
    "Reactive Attachment": [],
    "Pyromania": ["Pathological Fire Setting"],
    "Othello": ["Morbid Jealousy", "Delusional Jealousy", "Pathological Jealousy", "Sexual Jealousy"],
    "Disinhibited Social Engagement": ["Disinhibited Attachment"],
    "Schizoaffective": ["Schizo-affective Psychosis", "Schizo-affective Schizophrenia", "Schizophreniform Psychosis"],
    "Erotomanic": ["De Clérambault's", "De Clérambault", "De Clerambault", "Love Delusion", "Erotomania"],
    "Dementia pugilistica": ["Punch Drunk", "Chronic Traumatic Encephalopathy"],
    "Olfactory Reference": [],
    "Hypergraphia": [],
    "Wendigo Psychosis": ["Witiko Psychosis"],
    "Body Integrity Dysphoria": ["Body Integrity Identity", "Xenomelia", "Apotemnophilia", "Amputee Identity"],
    "Koro": ["Genital Retraction"],
    "Dissociative Fugue": ["Psychogenic Fugue", "Dissociative Amnesia with Fugue"],
    "Delusional": ["Paranoia"],
    "Anorexia nervosa": ["Anorexia"],
    "Impulse Control": ["Impulsivity"],
    "Postpartum Psychosis": ["Puerperal Psychosis", "Postnatal Psychosis"],
    "Savant": ["Savantism", "Idiot Savant"],
    "Brief Psychotic": ["Brief Reactive Psychosis", "Atypical Psychosis", "Bouffée Délirante", "Bouffee Delirante"],
    "Schizotypal Personality": ["Schizotypal"],
    "Selective Mutism": ["Situational Mutism"],
    "Kleine-Levin": ["Familial Hibernation", "Sleeping Beauty"],
    "Capgras": ["Delusion of Doubles"],
    "Narcissistic Personality": ["Grandiosity"],
    "Circadian Rhythm Sleep-Wake": ["Sleep-Wake Cycle"],
    "Rumination": ["Merycism"],
    "Cyclothymic": ["Cyclothymia", "Bipolar III"],
    "Walking Corpse": ["Cotard Delusion"],
    "Diogenes": ["Senile Squalor"],
    "Landau-Kleffner": ["Acquired Epileptic Aphasia"],
    "Psychogenic Amnesia": ["Dissociative Amnesia"],
    "Ekbom": ["Willis-Ekbom", "Restless Legs"],
    "Stendhal": ["Florence Syndrome", "Art-Induced Psychosis"],
    "Fregoli Delusion": ["Fregoli"],
    "Reduplicative Paramnesia": [],
    "Histrionic Personality": ["Dramatic Personality"],
    "Autosarcophagy": ["Self-Cannibalism"],
    "Ganser": ["Hysterical Pseudodementia", "Prison Psychosis", "Balderdash", "Vorbeigehen", "Vorbeireden"],
    "Kleptomania": ["Compulsive Stealing"],
    "Boanthropy": ["Clinical Lycanthropy"],
    "Avoidant Personality": ["Anxious Personality"],
    "Hallucinogen-Induced Psychotic": ["Drug-Induced Psychosis", "Psychedelic Psychosis"],
    "Bachmann-Bupp": ["ODC1 Gain-of-Function"],
    "Factitious": ["Munchausen"],
    "Hyperthymesia": ["Highly Superior Autobiographical Memory"],
    "Intermetamorphosis": [],
    "Palilalia": ["Repetitive Speech"],
    "Scribomania": ["Graphomania"],
    "Antisocial Personality Disorder": [],
    "Childhood Disintegrative Disorder": ["Heller’s", "Heller", "Hellers"]
}

# === Pertinent Technologies (minor fixes; removed duplicated DBT under MBSR) ===
PT_SYNONYMS = {
    "Digital Health Tools": ["Mobile Health Apps", "Health Information Technology", "Health Monitoring Wearable Devices", "Telehealth", "Telemedicine", "Personalized Medicine", "Care Support Tools"],
    "Virtual Reality Exposure Therapy": ["VR Exposure Therapy", "Virtual Reality Therapy", "VR Immersion Therapy", "Simulated Therapy", "Computerized CBT", "Computerized Cognitive Behavioral Therapy"],
    "Brain Stimulation Technologies": ["Neurostimulation Techniques", "Deep Brain Stimulation"],
    "Eye Movement Desensitization and Reprocessing": ["EMDR Therapy", "Eye Movement Therapy"],
    "Cognitive Assistive Technologies": ["AI Cognitive Aids"],
    "Electroencephalography": ["EEG", "Brain Activity Scanning"],
    "Transcranial Magnetic Stimulation": ["Repetitive Transcranial Magnetic Stimulation", "Non-Invasive Brain Stimulation"],
    "Brain-Computer Interface": ["Direct Neural Interface", "Neural Interface"],
    "Augmentative Communication Devices": ["Speech Generating Devices", "Speech Assistive Tools", "Text-to-Speech Devices"],
    "Neurofeedback Systems": ["EEG Biofeedback Therapy", "Neurobiofeedback"],
    "Biofeedback Devices": ["Physiological Monitoring Tools"],
    "Metaverse": ["Immersive Virtual Environments", "Extended Reality"],
    "Genetic Testing": ["Genetic Screening", "Genomic Screening", "DNA Profiling"],
    "Personalized Medicine": ["Precision Medicine", "Customized Medicine"],
    "Neuromodulation Techniques": ["Vagus Nerve Stimulation", "Brain Modulation", "Deep Brain Stimulation", "Spinal Cord Stimulation"],
    "Resting-state Functional Magnetic Resonance Imaging": ["rs-fMRI", "Brain Network Mapping"],
    "Voxel-based Lesion-Symptom Mapping": ["Voxel-Based Symptom-Lesion Mapping", "Neuroimaging Analysis"],
    "Neuroplasticity Techniques": ["Cognitive Rehabilitation", "Brain Adaptation Training"],
    "Blockchain for Data Protection": ["Decentralized Data Security", "Encrypted Healthcare Records"],
    "Privacy-Preserving AI in Digital Mental Health": ["Federated Learning", "Secure AI Models"],
    "Secure Data Storage for Patient Records": ["HIPAA-Compliant Cloud Storage", "Health Information Security", "Electronic Health Record Protection"],
    "Smart Wearable Mental Health Trackers": ["AI-Powered Wearables", "Digital Biomarkers"],
    "Digital Imaging Technologies for Brain Scanning": ["Neuroimaging AI", "Medical Image Analysis"],
    "Cognitive Behavioral Therapy": ["Psychotherapeutic Treatment"],
    "Dialectical Behavior Therapy": ["Emotional Regulation Therapy"],
    "Trauma-Focused CBT": ["TF-CBT", "PTSD Therapy"],
    "Exposure Therapy": ["Systematic Desensitization", "Gradual Exposure Therapy"],
    "Mindfulness-Based Stress Reduction": ["Mindfulness-Based Cognitive Therapy", "Mindfulness Therapy"],
    "Interpersonal Psychotherapy": ["Dynamic Interpersonal Therapy", "Relationship-Focused Therapy"],
    "Reality Testing Techniques": ["Cognitive Reality Checking", "Delusion Assessment"],
    "Psychoeducation Programs": ["Mental Health Awareness Training"],
    "Neurocognitive Training": ["Cognitive Enhancement Exercises"],
    "Antipsychotic Medications": ["Neuroleptics", "Dopamine Antagonists"],
    "Selective Serotonin Reuptake Inhibitors": ["SSRIs", "Antidepressant Therapy"],
    "Benzodiazepines": ["Anxiolytics", "Sedative-Hypnotics"],
    "Mood Stabilizers": ["Lithium", "Valproate", "Bipolar Treatment"],
    "Antidepressants": ["MAOIs", "TCAs", "SSRIs", "SNRIs"],
    "Neuroprotective Agents": ["Cognitive Enhancers", "Brain Health Supplements"],
    "Meditation and Relaxation Techniques": ["Mindfulness Meditation", "Deep Breathing Exercises"],
    "Creative Arts Therapies": ["Music Therapy", "Art Therapy", "Expressive Therapy"],
    "Expressive Writing & Journaling": ["Therapeutic Writing", "Emotional Expression"],
    "Animal-Assisted Interventions": ["Therapy Animals", "Emotional Support Animals"],
    "Dietary Interventions & Supplements": ["Nutritional Psychiatry", "Omega-3 Therapy"],
    "Traditional & Alternative Medicine Approaches": ["Ayurveda", "Acupuncture", "Herbal Remedies"],
    "Memory Retrieval Techniques": ["Cognitive Recall Training", "Mnemonic Strategies"],
    "Cognitive Enhancement Programs": ["Neuroplasticity Exercises", "Brain Training Apps"],
    "Social Skills Training": ["Interpersonal Effectiveness Training", "Autism Social Therapy"],
    "Emotion Regulation Training": ["DBT Emotion Skills", "Mindfulness Emotion Awareness"],
    "Behavioral Activation Therapy": ["BAT", "Depression Behavioral Therapy"],
    "Peer Support Programs & Online Communities": ["Mental Health Peer Networks"],
    "Stem Cell Therapy for Neurological Disorders": ["Regenerative Medicine", "Neural Repair"],
    "Regenerative Medicine Approaches": ["Tissue Engineering", "Organ Regeneration"],
    "Neurobiological Assessments for Mental Disorders": ["Brain Function Testing", "Biomarker Analysis"],
    "Sleep Pattern Monitoring & Manipulation": ["Sleep Hygiene Coaching", "Insomnia Therapy"],
    "Psychophysiological Metrics for Treatment Response": ["Heart Rate Variability", "Cortisol Levels"]
}

# === Flatten & canonical maps ===
ALL_DISEASE_TERMS = list(chain.from_iterable([[k] + v for k, v in DISEASE_SYNONYMS.items()]))
TERM_TO_CANONICAL_DISEASES = {t.lower(): k for k, vs in DISEASE_SYNONYMS.items() for t in [k] + vs}

ALL_PT_TERMS = list(chain.from_iterable([[k] + v for k, v in PT_SYNONYMS.items()]))
TERM_TO_CANONICAL_PT = {t.lower(): k for k, vs in PT_SYNONYMS.items() for t in [k] + vs}
