PT_SYNONYMS = {
    "Digital Health Tools": ["Mobile Health Apps", "Health Information Technology", "Health Monitoring Wearable Devices", "Telehealth", "Telemedicine", "Personalized Medicine", "Care Support Tools"],
    "Virtual Reality Exposure Therapy": ["VR Exposure Therapy", "Virtual Reality Therapy", "VR Immersion Therapy", "Simulated Therapy", "Computerized CBT", "Computerized Cognitive Behavioral Therapy"],
    "Brain Stimulation Technologies": ["Neurostimulation Techniques", "Deep brain stimulation"],
    "Eye Movement Desensitization and Reprocessing": ["EMDR Therapy", "eye movement therapy"],
    "Cognitive Assistive Technologies": ["AI Cognitive Aids"],
    "Electroencephalography": ["EEG", "Brain Activity Scanning"],
    "Transcranial Magnetic Stimulation": ["Repetitive Transcranial Magnetic Stimulation", "Non-Invasive Brain Stimulation"],
    "Brain-Computer Interface": ["Direct Neural Interface", "Neural Interface"],
    "Augmentative Communication Devices": ["Speech Generating Devices", "Speech Assistive Tools", "Text-to-Speech Devices"],
    "Neurofeedback Systems": ["EEG Biofeedback Therapy", "Neurobiofeedback"],
    "Biofeedback Devices": ["Physiological Monitoring Tools"],
    "Metaverse": ["Immersive Virtual Environments", "Extended Reality"],
    "Genetic Testing": ["Genetic Screening", "Genomic Screening", "DNA Profiling"],
    "Personalized Medicine": ["Precision Medicine", "Customized Medicine"],
    "Neuromodulation Techniques": ["Vagus Nerve Stimulation", "Brain Modulation", "Deep Brain Stimulation", "Spinal Cord Stimulation"],
    "Resting-state Functional Magnetic Resonance Imaging": ["rs-fMRI", "Brain Network Mapping"],
    "Voxel-based Lesion-Symptom Mapping": ["Voxel-Based Symptom-Lesion Mapping", "Neuroimaging Analysis"],
    "Neuroplasticity Techniques": ["Cognitive Rehabilitation", "Brain Adaptation Training"],
    "Blockchain for Data Protection": ["Decentralized Data Security", "Encrypted Healthcare Records"],
    "Privacy-Preserving AI in Digital Mental Health": ["Federated Learning", "Secure AI Models"],
    "Secure Data Storage for Patient Records": ["HIPAA-Compliant Cloud Storage", "Health Information Security", "Electronic Health Record Protection"],
    "Smart Wearable Mental Health Trackers": ["AI-Powered Wearables", "Digital Biomarkers"],
    "Digital Imaging Technologies for Brain Scanning": ["Neuroimaging AI", "Medical Image Analysis"],
    "Cognitive Behavioral Therapy": ["Psychotherapeutic Treatment"],
    "Dialectical Behavior Therapy": ["Emotional Regulation Therapy"],
    "Trauma-Focused CBT": ["TF-CBT", "PTSD Therapy"],
    "Exposure Therapy": ["Systematic Desensitization", "Gradual Exposure Therapy"],
    "Mindfulness-Based Stress Reduction": ["Mindfulness-Based Cognitive Therapy", "Mindfulness Therapy", "Dialectical Behavior Therapy"],
    "Interpersonal Psychotherapy": ["Dynamic Interpersonal Therapy", "Relationship-Focused Therapy"],
    "Reality Testing Techniques": ["Cognitive Reality Checking", "Delusion Assessment"],
    "Psychoeducation Programs": ["Mental Health Awareness Training"],
    "Neurocognitive Training": ["Cognitive Enhancement Exercises"],
    "Antipsychotic Medications": ["Neuroleptics", "Dopamine Antagonists"],
    "Selective Serotonin Reuptake Inhibitors": ["SSRIs", "Antidepressant Therapy"],
    "Benzodiazepines": ["Anxiolytics", "Sedative-Hypnotics"],
    "Mood Stabilizers": ["Lithium", "Valproate", "Bipolar Treatment"],
    "Antidepressants": ["MAOIs", "TCAs", "SSRIs", "SNRIs"],
    "Neuroprotective Agents": ["Cognitive Enhancers", "Brain Health Supplements"],
    "Meditation and Relaxation Techniques": ["Mindfulness Meditation", "Deep Breathing Exercises"],
    "Creative Arts Therapies": ["Music Therapy", "Art Therapy", "Expressive Therapy"],
    "Expressive Writing & Journaling": ["Therapeutic Writing", "Emotional Expression"],
    "Animal-Assisted Interventions": ["Therapy Animals", "Emotional Support Animals"],
    "Dietary Interventions & Supplements": ["Nutritional Psychiatry", "Omega-3 Therapy"],
    "Traditional & Alternative Medicine Approaches": ["Ayurveda", "Acupuncture", "Herbal Remedies"],
    "Memory Retrieval Techniques": ["Cognitive Recall Training", "Mnemonic Strategies"],
    "Cognitive Enhancement Programs": ["Neuroplasticity Exercises", "Brain Training Apps"],
    "Social Skills Training": ["Interpersonal Effectiveness Training", "Autism Social Therapy"],
    "Emotion Regulation Training": ["DBT Emotion Skills", "Mindfulness Emotion Awareness"],
    "Behavioral Activation Therapy": ["BAT", "Depression Behavioral Therapy"],
    "Peer Support Programs & Online Communities": ["Mental Health Peer Networks"],
    "Stem Cell Therapy for Neurological Disorders": ["Regenerative Medicine", "Neural Repair"],
    "Regenerative Medicine Approaches": ["Tissue Engineering", "Organ Regeneration"],
    "Neurobiological Assessments for Mental Disorders": ["Brain Function Testing", "Biomarker Analysis"],
    "Sleep Pattern Monitoring & Manipulation": ["Sleep Hygiene Coaching", "Insomnia Therapy"],
    "Psychophysiological Metrics for Treatment Response": ["Heart Rate Variability", "Cortisol Levels"]
}

def generate_pt_variations(term):
    return [f"{term} Technology", f"{term} Tool", f"{term} System"]

EXPANDED_PT_LIST = [
    variation for term in PT_SYNONYMS.keys() for variation in generate_pt_variations(term)
]
